/**
 * Plan resolver utilities
 * Replaces: gk-set-active-plan.cjs (setActivePlan function)
 */

import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync, statSync } from 'fs';
import { join, basename } from 'path';
import { Plan } from './types.js';
import { getPlansDir, getLocalEnvPath } from '../../utils/paths.js';
import { getActivePlan, getActiveGkSessionId, getProjectDir, readEnv } from '../session/env.js';
import { getSession } from '../session/manager.js';
import { setActivePlan as sessionSetActivePlan } from '../session/writer.js';

/**
 * List all plans in project
 */
export function listPlans(projectDir?: string): Plan[] {
  const plansDir = getPlansDir(projectDir);

  if (!existsSync(plansDir)) {
    return [];
  }

  const activePlan = getActivePlan();
  const dirs = readdirSync(plansDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  return dirs.map(name => {
    const path = join(plansDir, name);
    const planFile = join(path, 'plan.md');
    let createdAt = '';

    // Try to get creation date from plan.md or folder name
    if (existsSync(planFile)) {
      const stat = statSync(planFile);
      createdAt = stat.birthtime.toISOString();
    }

    return {
      name,
      path,
      createdAt,
      isActive: name === activePlan,
    };
  });
}

/**
 * Create a new plan
 */
export function createPlan(name: string, projectDir?: string): Plan {
  const plansDir = getPlansDir(projectDir);
  const planPath = join(plansDir, name);

  if (!existsSync(plansDir)) {
    mkdirSync(plansDir, { recursive: true });
  }

  if (existsSync(planPath)) {
    throw new Error(`Plan already exists: ${name}`);
  }

  // Create plan structure
  mkdirSync(planPath, { recursive: true });
  mkdirSync(join(planPath, 'research'), { recursive: true });
  mkdirSync(join(planPath, 'artifacts'), { recursive: true });

  // Create plan.md template
  const template = `# ${name}

## Overview

[Describe the plan objectives here]

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

## Notes

`;

  writeFileSync(join(planPath, 'plan.md'), template);

  return {
    name,
    path: planPath,
    createdAt: new Date().toISOString(),
    isActive: false,
  };
}

/**
 * Set active plan in session file AND .env
 * Matches gk-set-active-plan.cjs behavior:
 * 1. Updates session.activePlan in ~/.gemkit/projects/{projectDir}/gk-session-{gkSessionId}.json
 * 2. Updates ACTIVE_PLAN in .gemini/.env
 */
export function setActivePlan(name: string, projectDir?: string): boolean {
  // Get active session ID and project dir from .env
  const gkSessionId = getActiveGkSessionId();
  if (!gkSessionId) {
    // No active session - just update env directly
    const envPath = getLocalEnvPath(projectDir);
    const env = readEnv();

    // Build new env content with ACTIVE_PLAN
    const content = [
      '# Auto-generated by gemkit-cli',
      `# Updated at: ${new Date().toISOString()}`,
      '',
      '# GEMKIT IDs',
      `ACTIVE_GK_SESSION_ID=${env.ACTIVE_GK_SESSION_ID || ''}`,
      `GK_PROJECT_HASH=${env.GK_PROJECT_HASH || ''}`,
      `PROJECT_DIR=${env.PROJECT_DIR || ''}`,
      '',
      '# GEMINI IDs (mapped)',
      `ACTIVE_GEMINI_SESSION_ID=${env.ACTIVE_GEMINI_SESSION_ID || ''}`,
      `GEMINI_PROJECT_HASH=${env.GEMINI_PROJECT_HASH || ''}`,
      '',
      '# PLAN INFO',
      `ACTIVE_PLAN=${name}`,
      `SUGGESTED_PLAN=${env.SUGGESTED_PLAN || ''}`,
      `PLAN_DATE_FORMAT=${env.PLAN_DATE_FORMAT || ''}`,
      ''
    ].join('\n');

    writeFileSync(envPath, content);
    return true;
  }

  const projDir = getProjectDir(projectDir);

  // Verify session exists
  const session = getSession(projDir, gkSessionId);
  if (!session) {
    // Session not found - just update env
    const envPath = getLocalEnvPath(projectDir);
    const env = readEnv();

    const content = [
      '# Auto-generated by gemkit-cli',
      `# Updated at: ${new Date().toISOString()}`,
      '',
      '# GEMKIT IDs',
      `ACTIVE_GK_SESSION_ID=${env.ACTIVE_GK_SESSION_ID || ''}`,
      `GK_PROJECT_HASH=${env.GK_PROJECT_HASH || ''}`,
      `PROJECT_DIR=${env.PROJECT_DIR || ''}`,
      '',
      '# GEMINI IDs (mapped)',
      `ACTIVE_GEMINI_SESSION_ID=${env.ACTIVE_GEMINI_SESSION_ID || ''}`,
      `GEMINI_PROJECT_HASH=${env.GEMINI_PROJECT_HASH || ''}`,
      '',
      '# PLAN INFO',
      `ACTIVE_PLAN=${name}`,
      `SUGGESTED_PLAN=${env.SUGGESTED_PLAN || ''}`,
      `PLAN_DATE_FORMAT=${env.PLAN_DATE_FORMAT || ''}`,
      ''
    ].join('\n');

    writeFileSync(envPath, content);
    return true;
  }

  // Update session file AND env file using session writer
  return sessionSetActivePlan(projDir, gkSessionId, name);
}

/**
 * Get plan info
 */
export function getPlanInfo(name: string, projectDir?: string): Plan | null {
  const plansDir = getPlansDir(projectDir);
  const planPath = join(plansDir, name);

  if (!existsSync(planPath)) {
    return null;
  }

  const activePlan = getActivePlan();

  return {
    name,
    path: planPath,
    createdAt: '',
    isActive: name === activePlan,
  };
}
